#581 Update adam dependency version to 0.35.0  (#584)
* Update adam dependency version to 0.35.0.

* downgrade maven-resources: broken symlink function

Co-authored-by: Michael L Heuer <heuermh@acm.org>

diff --git a/scripts/jenkins-test b/scripts/jenkins-test
--- a/scripts/jenkins-test
+++ b/scripts/jenkins-test
@@ -85,31 +85,6 @@ fi
 
 set -e
 
-# move to Scala 2.11 if requested
-if [ ${SCALAVER} == 2.11 ];
-then
-    set +e
-    ./scripts/move_to_scala_2.11.sh
-    set -e
-fi
-
-
-# move to Scala 2.12 if requested
-if [ ${SCALAVER} == 2.12 ];
-then
-    set +e
-    ./scripts/move_to_scala_2.12.sh
-    set -e
-fi
-
-# move to Spark 2.x if requested
-if [ ${SPARK_MAJOR_VERSION} == 2 ];
-then
-    set +e
-    ./scripts/move_to_spark_2.sh
-    set -e
-fi
-
 # print versions
 echo "Testing MANGO version ${VERSION} on Spark ${SPARK_VERSION} and Hadoop ${HADOOP_VERSION}"
 
@@ -264,6 +239,8 @@ do
     set -e -x
 done
 
+set -e -x
+
 # test mango submit
 MANGO_BROWSER_LOGS=${MANGO_TMP_DIR}/mango-submit.log
 bash -xv ${PROJECT_ROOT}/example-files/browser-scripts/run-example.sh &> ${MANGO_BROWSER_LOGS} &
@@ -279,7 +256,8 @@ curl -s -N \
     http://localhost:8080/reads/search | grep alignments
 
 if [[ $? != 0 ]]; then
-    echo
+    echo "grep for alignments failed"
+    cat ${MANGO_BROWSER_LOGS}
     exit 1
 fi
 
