updated curl to silently fail

diff --git a/scripts/jenkins-test b/scripts/jenkins-test
--- a/scripts/jenkins-test
+++ b/scripts/jenkins-test
@@ -238,17 +238,27 @@ then
     sleep 10
 
     # make sure server responds to POST for reads and variants
-    curl \
+    curl -s -N \
     --header "Content-type: application/json" \
     --request POST \
     --data "{\"pageToken\":null,\"pageSize\":200,\"readGroupIds\":[\"chr17_7500000-7515000_sam\"],\"referenceId\":\"chr17\",\"start\":1,\"end\":100}"  \
-    http://localhost:8080/reads/search
+    http://localhost:8080/reads/search | grep alignments
 
-    curl \
-    --header "Content-type: application/json" \
-    --request POST \
-    --data "{\"variantSetId\":\"ALL_chr17_7500000-7515000_phase3_shapeit2_mvncall_integrated_v5a_20130502_genotypes_vcf\",\"pageToken\":null,\"pageSize\":400,\"referenceName\":\"chr17\",\"callSetIds\":[],\"start\":7500000,\"end\":7515000}"  \
-    http://localhost:8080/variants/search
+    if [[ $? != 0 ]]; then
+        echo "invalid alignments"
+        exit 1
+    fi
+
+    curl -s -N \
+        --header "Content-type: application/json" \
+        --request POST \
+        --data "{\"variantSetId\":\"ALL_chr17_7500000-7515000_phase3_shapeit2_mvncall_integrated_v5a_20130502_genotypes_vcf\",\"pageToken\":null,\"pageSize\":400,\"referenceName\":\"chr17\",\"callSetIds\":[],\"start\":7500000,\"end\":7515000}"  \
+        http://localhost:8080/variants/search | grep variants
+
+    if [[ $? != 0 ]]; then
+        echo "invalid variants"
+        exit 1
+    fi
 
     # get processes with mango prefix
     PROCESSES=( $(ps aux | grep -F 'browser-scripts/run-example.sh' | grep -v -F 'grep' | awk '{ print $2 }') )
