debugging jenkins test

diff --git a/scripts/jenkins-test b/scripts/jenkins-test
--- a/scripts/jenkins-test
+++ b/scripts/jenkins-test
@@ -239,6 +239,8 @@ do
     set -e -x
 done
 
+set -e -x
+
 # test mango submit
 MANGO_BROWSER_LOGS=${MANGO_TMP_DIR}/mango-submit.log
 bash -xv ${PROJECT_ROOT}/example-files/browser-scripts/run-example.sh &> ${MANGO_BROWSER_LOGS} &
@@ -254,7 +256,8 @@ curl -s -N \
     http://localhost:8080/reads/search | grep alignments
 
 if [[ $? != 0 ]]; then
-    echo
+    echo "grep for alignments failed"
+    cat ${MANGO_BROWSER_LOGS}
     exit 1
 fi
 
