added python3 tests for jenkins

diff --git a/scripts/jenkins-test b/scripts/jenkins-test
--- a/scripts/jenkins-test
+++ b/scripts/jenkins-test
@@ -149,14 +149,6 @@ then
 
     pushd $MANGO_TMP_DIR
 
-    # create a conda environment for python build, if necessary
-    uuid=$(uuidgen)
-    conda create -y -q -n mango-build-${uuid} python=2.7 anaconda
-    source activate mango-build-${uuid}
-
-    # install npm and node in the venv for mango-viz
-    conda install nodejs
-
     # what hadoop version are we on? format string for downloading spark assembly
     if [[ $HADOOP_VERSION =~ ^2\.6 ]]; then
         HADOOP=hadoop2.6
@@ -187,64 +179,82 @@ then
     ASSEMBLY_JAR="$(ls -1 "$ASSEMBLY_DIR" | grep "^mango-assembly[0-9A-Za-z\_\.-]*\.jar$" | grep -v javadoc | grep -v sources || true)"
     export PYSPARK_SUBMIT_ARGS="--jars ${ASSEMBLY_DIR}/${ASSEMBLY_JAR} --driver-class-path ${ASSEMBLY_DIR}/${ASSEMBLY_JAR} pyspark-shell"
 
+    # create a conda environment for python build, if necessary
+    pythons=( 2.7 3.6 )
+    for python in ${pythons[*]}
+    do
+        uuid=$(uuidgen)
+        conda create -q -n mango-build-${uuid} python=${python} anaconda
+        source activate mango-build-${uuid}
 
-    # prepare mango python
-    pushd mango-python
-    make prepare
-    popd
+        # install npm and node in the venv for mango-viz
+        conda install nodejs
 
+        # prepare mango python
+        pushd mango-python
+        make prepare
+        popd
 
-    # we can run the python build, now that we have a spark executable
-	  mvn -U \
-        -P python,distribution \
-        package \
-        -DskipTests \
-        -Dhadoop.version=${HADOOP_VERSION} \
-        -Dspark.version=${SPARK_VERSION}
+        # we can run the python build, now that we have a spark executable
+        mvn -U \
+            -P python,distribution \
+            package \
+            -DskipTests \
+            -Dhadoop.version=${HADOOP_VERSION} \
+            -Dspark.version=${SPARK_VERSION}
 
-    # clean mango python
-    pushd mango-python
-    make clean
-    popd
+        # clean mango python
+        pushd mango-python
+        make clean
+        popd
 
-    # prepare mango viz
-    pushd mango-viz
-    make prepare
-    popd
+        # prepare mango viz
+        pushd mango-viz
+        make prepare
+        popd
 
-    # run the widgets tests (mango-viz)
-    mvn -P widgets test
+        # run the widgets tests (mango-viz)
+        mvn -P widgets test
 
-    # clean mango viz
-    pushd mango-viz
-    make clean
-    popd
+        # clean mango viz
+        pushd mango-viz
+        make clean
+        popd
 
-    # make sure that the distribution package contains an egg
-    # if no assembly jar is found, this will exit with code 1 and fail the build
-    tar tzvf mango-distribution/target/mango-distribution*-bin.tar.gz | \
-        grep bdgenomics.mango | \
-        grep egg
+    	# deactivate and remove the conda env
+    	source deactivate
+    	conda remove -n mango-build-${uuid} --all
 
-    # test mango notebook, output to temporary log file
-    MANGO_NOTEBOOK_LOGS=${MANGO_TMP_DIR}/mango-notebook.log
-    bash -xv ${PROJECT_ROOT}/bin/mango-notebook  &> ${MANGO_NOTEBOOK_LOGS} &
+    	# copy python targets back
+    	cp -r mango-python/target ${PROJECT_ROOT}/mango-python/
 
-    # sleep for 2 seconds to let mango-notebook start up
-    sleep 2
+        # make sure that the distribution package contains an egg
+        # if no assembly jar is found, this will exit with code 1 and fail the build
+        tar tzvf mango-distribution/target/mango-distribution*-bin.tar.gz | \
+            grep bdgenomics.mango | \
+            grep egg
 
-    # if mango-notebook fails, then trying to kill the process will fail
-    if kill $! ; then
-        echo "Mango Notebook Succeeded"
-        # kill jupyter notebook
-        pkill -f jupyter-notebook
-    else
-        echo "Mango Notebook failed with logs:"
-        cat ${MANGO_NOTEBOOK_LOGS}
-        # clean up
-        rm -rf ${MANGO_TMP_DIR}
-        exit 1
-    fi
+        # test mango notebook, output to temporary log file
+        MANGO_NOTEBOOK_LOGS=${MANGO_TMP_DIR}/mango-notebook.log
+        bash -xv ${PROJECT_ROOT}/bin/mango-notebook  &> ${MANGO_NOTEBOOK_LOGS} &
+
+        # sleep for 2 seconds to let mango-notebook start up
+        sleep 2
+
+        # if mango-notebook fails, then trying to kill the process will fail
+        if kill $! ; then
+            echo "Mango Notebook Succeeded"
+            # kill jupyter notebook
+            pkill -f jupyter-notebook
+        else
+            echo "Mango Notebook failed with logs:"
+            cat ${MANGO_NOTEBOOK_LOGS}
+            # clean up
+            rm -rf ${MANGO_TMP_DIR}
+            exit 1
+        fi
+
+    done
 
     # test mango submit
     MANGO_BROWSER_LOGS=mango-submit.log
